Gapminder/ddf-validation

- .eslintrc.json
- index.js
- lib/data/db.js
- lib/data/directory-descriptor.js
- lib/data/root.js
- lib/utils/args.js
- lib/utils/file.js
- lib/utils/index.js
- package.json
- test/.eslintrc.json
- test/db.spec.js
- test/ddf-root.spec.js
- test/test-utils.js
> feat(eslint): eslint integration

- .eslintrc.json
- .gitignore
- index.js
- lib/data/db.js
- lib/data/directory-descriptor.js
- lib/data/root.js
- lib/utils/args.js
- lib/utils/file.js
- lib/utils/index.js
- package.json
- test/.eslintrc.json
- test/db.spec.js
- test/ddf-root.spec.js
- test/fixtures/good-folder/ddf--concepts.csv
- test/fixtures/good-folder/ddf--list--geo.csv
- test/test-utils.js
also added new stub data and fixed existing stub data
Closes #12
> feat(lokijs,tests): LokiJS integration

- index.js
- lib/data/file-descriptor.js
- lib/ddf-definitions/data-point.js
- lib/ddf-definitions/ddf-data.js
- lib/ddf-rules/data-point-rules.js
- lib/ddf-rules/registry.js
- lib/utils/file.js
- test/ddf-data-point-rules.spec.js
- test/fixtures/good-folder/ddf--datapoints--pop--by--country--year.csv
- test/fixtures/rules-cases/data-point-value-not-num/ddf--concepts--measures.csv
- test/fixtures/rules-cases/data-point-value-not-num/ddf--concepts.csv
- test/fixtures/rules-cases/data-point-value-not-num/ddf--datapoints--pop--by--country--year.csv
- test/fixtures/rules-cases/data-point-value-not-num/ddf--entities--geo--country.csv
> feat(data point): data point validation skeleton

- index.js
- lib/ddf-definitions/ddf-data.js
- lib/ddf-definitions/ddf-index-generator.js
- package.json
- test/ddf-index-generator.spec.js
> fixed(ddf--index): entities

- README.md
- doc/developer-guide.md
- index.js
- lib/ddf-definitions/ddf-data-set.js
- lib/ddf-definitions/ddf-index-generator.js
- lib/ddf-rules/concept-rules.js
- lib/ddf-rules/data-point-rules.js
- lib/ddf-rules/entity-rules.js
- lib/ddf-rules/general-rules.js
- lib/ddf-rules/index-rules.js
- test/concept-rules.spec.js
- test/ddf-data-point-rules.spec.js
- test/ddf-data.spec.js
- test/ddf-index-rules.spec.js
- test/entry-rules.spec.js
- test/general-rules.spec.js
> docs(dev-guide): developer guide

- doc/rules/NON_CONCEPT_HEADER.md
- lib/ddf-rules/concept-rules.js
- lib/ddf-rules/registry.js
- test/concept-rules.spec.js
- test/fixtures/rules-cases/non-concept-header/ddf--concepts--measures.csv
- test/fixtures/rules-cases/non-concept-header/ddf--concepts.csv
- test/fixtures/rules-cases/non-concept-header/ddf--datapoints--pop--by--country--year.csv
- test/fixtures/rules-cases/non-concept-header/ddf--entities--geo--country.csv
> feat(NON_CONCEPT_HEADER): NON_CONCEPT_HEADER rule

- doc/rules/EMPTY_CONCEPT_ID.md
- lib/ddf-rules/concept-rules.js
- lib/ddf-rules/registry.js
- test/concept-rules.spec.js
- test/fixtures/rules-cases/empty-concept-id/ddf--concepts.csv
> feat(rule): EMPTY_CONCEPT_ID

- doc/rules/FILENAME_DOES_NOT_MATCH_HEADER.md
- lib/data/ddf-index.js
- lib/ddf-definitions/ddf-data-set.js
- lib/ddf-rules/general-rules.js
- lib/ddf-rules/registry.js
- test/fixtures/rules-cases/filename-does-not-match-header/ddf--concepts--measures.csv
- test/fixtures/rules-cases/filename-does-not-match-header/ddf--concepts.csv
- test/fixtures/rules-cases/filename-does-not-match-header/ddf--datapoints--pop--by--country--year.csv
- test/fixtures/rules-cases/filename-does-not-match-header/ddf--entities--geo--country.csv
- test/general-rules.spec.js
> feat(rule): FILENAME_DOES_NOT_MATCH_HEADER rule implementation

- doc/rules/CONCEPTS_NOT_FOUND.md
- lib/ddf-rules/concept-rules.js
- lib/ddf-rules/registry.js
- test/concept-rules.spec.js
- test/fixtures/rules-cases/concepts-not-found/ddf--entities--geo--country.csv
> feat(rule): CONCEPTS_NOT_FOUND rule providing

- doc/rules/NON_CONCEPT_HEADER.md
- lib/ddf-rules/concept-rules.js
- test/concept-rules.spec.js
- test/fixtures/good-folder/ddf--concepts.csv
- test/fixtures/rules-cases/non-concept-header/ddf--concepts--measures.csv
> chore(rule): add extra functionality to NON_CONCEPT_HEADER rule

- index.js
- lib/ddf-definitions/data-point.js
- lib/ddf-definitions/ddf-data-set.js
- lib/ddf-rules/data-point-rules.js
- lib/utils/file.js
- package.json
- test/ddf-data-point-rules.spec.js
> fixed(out of memory): out of memory on huge data points set

- .travis.yml
- lib/ddf-rules/data-point-rules.js
- lib/ddf-rules/registry.js
- test/ddf-data-point-rules.spec.js
> feat(rule): MEASURE_VALUE_NOT_NUMERIC rule providing

- doc/rules/INVALID_DRILL_UP.md
- lib/ddf-rules/concept-rules.js
- lib/ddf-rules/registry.js
- test/concept-rules.spec.js
- test/fixtures/rules-cases/invalid-drill-up/ddf--concepts.csv
> feat(rule): INVALID_DRILL_UP rule providing

- lib/ddf-definitions/ddf-json-corrector.js
> fixed(utils): JSON auto correction

- README.md
- cli.js
- index.js
- lib/data/db.js
- lib/ddf-rules/concept-rules.js
- package.json
- test/api.spec.js
> feat(api): external validation API was provided

- lib/ddf-rules/concept-rules.js
- test/concept-rules.spec.js
- test/fixtures/rules-cases/invalid-drill-up/ddf--concepts.csv
> fixed(rule): INVALID_DRILL_UP was fixed

- lib/data/ddf-index.js
- lib/data/directory-descriptor.js
- lib/ddf-definitions/ddf-data-set.js
- lib/ddf-rules/general-rules.js
- lib/ddf-rules/index-rules.js
> feat(index): clear approach for validation/indexing

- index.js
- lib/data/ddf-index.js
- lib/data/directory-descriptor.js
- lib/data/file-descriptor.js
- lib/data/root.js
- lib/ddf-definitions/ddf-data-set.js
- lib/ddf-rules/index-rules.js
- lib/utils/args.js
- test/ddf-root.spec.js
> feat(general): indexless validation mode was provided

- README.md
- lib/data/ddf-index.js
- lib/data/root.js
also excludeDirs mode was fixed
Closes #164
> fixed(general): index heuristic

- README.md
- index.js
- lib/utils/args.js
> chore(params): datapointless mode

- lib/data/root.js
> fix(windows): error in windows

- doc/rules/EMPTY_DATA.md
- lib/data/directory-descriptor.js
- lib/data/file-descriptor.js
- lib/ddf-rules/general-rules/empty-data.js
- lib/ddf-rules/general-rules/index.js
- lib/ddf-rules/registry.js
- test/empty-data.spec.js
- test/fixtures/rules-cases/empty-data/ddf--concepts--measures.csv
- test/fixtures/rules-cases/empty-data/ddf--concepts.csv
- test/fixtures/rules-cases/empty-data/ddf--entities--geo--country.csv
> feat(rule): EMPTY_DATA rule providing

- lib/ddf-rules/general-rules/unexpected-data.js
> fixed(mode): unexpected file processing via cli - api

- lib/ddf-rules/index-rules.js
- test/api.spec.js
> fix(index): unexpected 'index missing' warning

- lib/data/data-package.js
primaryKey for entities logic
Closes #278
> fixed(datapackage): datapackage generation functionality

- src/cli-logic.ts
- src/data/data-package.ts
- src/utils/args.ts
> feat(datapackage): smart datapackage creation functionality

- src/data/data-package.ts
- src/utils/args.ts
also datapackage creation functionality was fixed
Closes #381 #236
> chore(general): allow space based directories for --exclude-dirs mode

- package.json
- src/cli-logic.ts
- src/cli.js
- src/data/data-package.ts
- src/data/ddf-schema.ts
> chore(datapackage): nested folder supporting﻿⁠⁠ for ﻿⁠⁠⁠⁠datapackage

- src/ddf-definitions/data-point.ts
- src/ddf-definitions/ddf-data-set.ts
- src/ddf-rules/general-rules/wrong-data-point-header.ts
- src/ddf-rules/index.ts
- test/api.spec.ts
- test/fixtures/rules-cases/wrong-data-point-header/datapackage.json
- test/fixtures/rules-cases/wrong-data-point-header/ddf--datapoints--pop--by--country--year.csv
- test/general-rules.spec.ts
> chore(rule): refactor WRONG_DATA_POINT_HEADER rule

- README.md
- package.json
- src/cli-logic.ts
- src/data/file-descriptor.ts
- src/data/shared.ts
- src/index.ts
- src/shared.ts
- src/thread.ts
- src/utils/args.ts
- src/utils/issues-filter.ts
- test/api.spec.ts
- tsconfig.json
> feat(general): datapoint processing in different threads

- src/ddf-rules/data-package-rules/confused-fields.ts
- src/ddf-rules/data-point-rules/duplicated-data-point-key.ts
- src/ddf-rules/index.ts
- src/ddf-rules/translation-rules/duplicated-data-point-translation-key.ts
- src/index.ts
- src/shared.ts
- src/utils/file.ts
- src/utils/issues-filter.ts
- test/data-point-rules.spec.ts
> fixed(productivity): clear unused memory

- .gitignore
- package.json
- src/ddf-rules/data-point-rules/duplicated-data-point-key.ts
- src/ddf-rules/translation-rules/duplicated-data-point-translation-key.ts
- src/index.ts
- src/shared.ts
- test/data-point-rules.spec.ts
- test/translation-rules.spec.ts
> fixed(rules): error in datapoint duplications

- package.json
- src/data/ddf-schema.ts
> fixed(datapackage): datapackage.json creation functionality crashes

- README.md
- package.json
- src/cli-logic.ts
- src/data/data-package.ts
- src/utils/args.ts
- test/fixtures/data-package/ddf--unpop--wpp_population/datapackage.template.json
> chore(datapackage): minimize datapackage.json size

- package.json
- src/data/ddf-root.ts
- src/ddf-rules/registry.ts
> chore(general): increase validation speed in datapointless mode

- package.json
- src/ddf-rules/data-point-rules/shared.ts
- test/api.spec.ts
- test/data-point-rules.spec.ts
- test/fixtures/rules-cases/data-point-unexpected-entity-value-2/ddf--concepts.csv
- test/fixtures/rules-cases/data-point-unexpected-entity-value-2/ddf--datapoints--pop--by--geo--year.csv
- test/fixtures/rules-cases/data-point-unexpected-entity-value-2/ddf--entities--geo.csv
> fixed(rules): fix DATA_POINT_UNEXPECTED_ENTITY_VALUE rule behavior

- package.json
- src/data/data-package.ts
- src/data/file-descriptor.ts
> fixed(general): fix validator's behavior under Windows

- package.json
- src/ddf-rules/data-point-rules/constraint-violation.ts
- src/ddf-rules/data-point-rules/shared.ts
- src/ddf-rules/data-point-rules/unexpected-entity-value.ts
- src/ddf-rules/data-point-rules/unexpected-time-value.ts
- test/data-point-rules.spec.ts
- test/fixtures/rules-cases/data-point-unexpected-entity-value/ddf--concepts.csv
- test/fixtures/rules-cases/data-point-unexpected-entity-value/ddf--datapoints--pop--by--country--year.csv
- test/fixtures/sankey/ddf--entities--phase.csv
> fix(rule): refactor and DATA_POINT_UNEXPECTED_ENTITY_VALUE rule

- package.json
- src/cli-logic.ts
- src/utils/args.ts
- src/utils/logger.ts
- test/api.spec.ts
- test/concept-rules.spec.ts
- test/csv-checker.spec.ts
- test/data-package-rules.spec.ts
- test/data-point-rules.spec.ts
- test/datapackage.spec.ts
- test/ddf-json-corrector.spec.ts
- test/ddf-root.spec.ts
- test/ddf-schema.spec.ts
- test/empty-data.spec.ts
- test/entity-rules.spec.ts
- test/general-rules.spec.ts
- test/issues-filter.spec.ts
- test/translation-rules.spec.ts
- test/unexpected-data.spec.ts
> feat(general): set --progress mode by default

- src/ddf-rules/entity-rules/unexisting-constraint-value.ts
- test/entity-rules.spec.ts
- test/fixtures/rules-cases/unexisting-constraint-value-2/datapackage.json
- test/fixtures/rules-cases/unexisting-constraint-value-2/ddf--concepts.csv
- test/fixtures/rules-cases/unexisting-constraint-value-2/ddf--datapoints--test_indicator--by--country-usa--year.csv
- test/fixtures/rules-cases/unexisting-constraint-value-2/ddf--entities--geo.csv
> fixed(rules): UNEXISTING_CONSTRAINT_VALUE raised incorrectly

- package.json
- src/index.ts
- src/shared.ts
- src/utils/index.ts
- src/utils/logger.ts
> fixed(general): SimpleValidator does not work (from WS+WSCli)

- package-lock.json
- package.json
> fixed(progressbar): Exception in södertörn dataset

- package.json
- src/data/ddf-schema.ts
> chore(datapackage): data in ddfSchema should be ordered

- src/index.ts
- src/utils/args.ts
> chore(general): at least one cpu should be free under --multithread mode

- package.json
- src/data/data-package.ts
- test/data-package-rules.spec.ts
- test/fixtures/rules-cases/dp-quoted-fields/datapackage.json
- test/fixtures/rules-cases/dp-quoted-fields/ddf--concepts--continuous.csv
- test/fixtures/rules-cases/dp-quoted-fields/ddf--concepts--discrete.csv
> fixed(datapackage rule): strip csv header quotes in all cases

- README.md
- package.json
- src/cli-logic.ts
- src/data/data-package.ts
- src/index.ts
> feat(api): move datapackage creation logic to separate api functionality

- package.json
- src/index.ts
> fixed(api): apply custom settings on StreamValidator

- package.json
- src/cli-logic.ts
- src/data/data-package.ts
- src/index.ts
- src/shared.ts
> chore(general): adapt to gapminder-offline

- src/cli-logic.ts
- src/ddf-rules/issue.ts
- src/index.ts
- src/utils/args.ts
> feat(issues view): output validation summary before validation errors

- doc/api-reference.md
- doc/user-guide.md
- src/ddf-rules/entity-rules/entity-value-as-entity-name.ts
- src/index.ts
also doc was fixed
Closes #500 #501
> fixed(misc): different fixes before release

- package.json
- src/data/data-package.ts
> fixed(general): catch lost datapackage schema validation error

- package.json
- src/cli-logic.ts
- src/data/ddf-schema.ts
> chore(general): provide more strict logic for ddfSchema creation

- src/ddf-rules/data-point-rules/duplicated-data-point-key.ts
- test/data-point-rules.spec.ts
> fixed(general): heap out of memory for faostat

- src/cli-logic.ts
- src/ddf-rules/concept-rules/non-concept-header.ts
- src/version.ts
- make output log valid JSON
- NON_CONCEPT_HEADER is reported for is-- headers
- fix app exit code
Closes #512 #511 #517
> chore(general): different fixes:

- src/data/data-package.ts
- test/datapackage.spec.ts
- test/fixtures/ddf--ws--testing/datapackage.json
- test/fixtures/results/datapackage/ddf--ws--testing.json
> fixed(datapackage creation): wrong datapackage.json creation behavior

- package.json
- src/ddf-definitions/constants.ts
- src/ddf-definitions/ddf-data-set.ts
- test/api.spec.ts
> fixed(general): unexpected issues under datapointless mode

- src/ddf-definitions/ddf-data-set.ts
- src/index.ts
- test/e2e.spec.ts
- test/fixtures/wrong-csv/ddf--entities--tag.csv
- test/unexpected-data.spec.ts
> fixed(main flow): catch errors regarding wrong csv structure
